version: '3'

services:
    mongo:
        image: mongo:4.2
        hostname: mongo
        ports:
          - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: secret
          MONGO_INITDB_DATABASE: pokedex
          MONGODB_PASS: secret
          MONGODB_DATABASE: pokedex
          MONGODB_USER: admin